# Generated by Django 5.0.2 on 2024-03-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_hotel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img',
            field=models.ImageField(default='img/default_image.jpg', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(default='img/default_image.jpg', upload_to='rooms'),
        ),
    ]
