# Generated by Django 5.0.2 on 2024-03-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_hotel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='booking.region'),
        ),
    ]
