# Generated by Django 5.0.2 on 2024-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_room_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='img',
            field=models.ImageField(default='default.png', upload_to='hotel_imgs/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(default='default.png', upload_to='room_imgs/'),
        ),
    ]
